---
# tasks file for docker

- name: Add docker yum repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker
  yum:
    name: '{{ docker_packages }}'
    state: installed

- name: Ensures docker config dir exists
  file:
    path: /etc/docker
    state: directory

- name: update docker daemon configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart docker
    - update aide

- name: Start and enable docker
  service:
    name: docker
    enabled: yes
    state: started

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

